//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Factura = new HashSet<Factura>();
            this.PagoDeFacturas = new HashSet<PagoDeFacturas>();
        }
    
        public decimal idCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public decimal DNI { get; set; }
        public string Mail { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Cod_Postal { get; set; }
        public System.DateTime Fecha_Nac { get; set; }
        public bool Activo { get; set; }
        public bool DatosErroneos { get; set; }
    
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<PagoDeFacturas> PagoDeFacturas { get; set; }
    }
}
