//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Comision> Comision { get; set; }
        public DbSet<DevolucionDeFacturas> DevolucionDeFacturas { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<FacturasDevolucion> FacturasDevolucion { get; set; }
        public DbSet<FacturasPago> FacturasPago { get; set; }
        public DbSet<FacturasRendicion> FacturasRendicion { get; set; }
        public DbSet<FormaDePago> FormaDePago { get; set; }
        public DbSet<Funcionalidad> Funcionalidad { get; set; }
        public DbSet<FuncionalidadesRol> FuncionalidadesRol { get; set; }
        public DbSet<Item_Factura> Item_Factura { get; set; }
        public DbSet<PagoDeFacturas> PagoDeFacturas { get; set; }
        public DbSet<Rendicion> Rendicion { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<RolesUsuario> RolesUsuario { get; set; }
        public DbSet<Rubro> Rubro { get; set; }
        public DbSet<Sucursal> Sucursal { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<UsuariosSucursal> UsuariosSucursal { get; set; }
    }
}
