//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevolucionDeFacturas
    {
        public DevolucionDeFacturas()
        {
            this.FacturasDevolucion = new HashSet<FacturasDevolucion>();
        }
    
        public decimal idDevolucion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Motivo { get; set; }
    
        public virtual ICollection<FacturasDevolucion> FacturasDevolucion { get; set; }
    }
}
