//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Factura = new HashSet<Factura>();
            this.Rendicion = new HashSet<Rendicion>();
        }
    
        public decimal idEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Cuit { get; set; }
        public string Direccion { get; set; }
        public decimal Rubro { get; set; }
        public bool Activa { get; set; }
    
        public virtual Rubro Rubro1 { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<Rendicion> Rendicion { get; set; }
    }
}
