//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasDevolucion
    {
        public decimal idFacturaDevolucion { get; set; }
        public decimal Devolucion { get; set; }
        public decimal FacturaPago { get; set; }
    
        public virtual DevolucionDeFacturas DevolucionDeFacturas { get; set; }
        public virtual FacturasPago FacturasPago { get; set; }
    }
}
