//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasPago
    {
        public FacturasPago()
        {
            this.FacturasDevolucion = new HashSet<FacturasDevolucion>();
        }
    
        public decimal idFacturaPago { get; set; }
        public decimal Pago { get; set; }
        public decimal Factura { get; set; }
    
        public virtual Factura Factura1 { get; set; }
        public virtual ICollection<FacturasDevolucion> FacturasDevolucion { get; set; }
        public virtual PagoDeFacturas PagoDeFacturas { get; set; }
    }
}
