//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.FacturasPago = new HashSet<FacturasPago>();
            this.FacturasRendicion = new HashSet<FacturasRendicion>();
            this.Item_Factura = new HashSet<Item_Factura>();
        }
    
        public decimal idFactura { get; set; }
        public decimal Cliente { get; set; }
        public decimal Empresa { get; set; }
        public decimal Nro_Factura { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.DateTime FechaVenc { get; set; }
        public decimal Importe { get; set; }
        public bool Pagada { get; set; }
        public bool Rendida { get; set; }
        public bool Activa { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual ICollection<FacturasPago> FacturasPago { get; set; }
        public virtual ICollection<FacturasRendicion> FacturasRendicion { get; set; }
        public virtual ICollection<Item_Factura> Item_Factura { get; set; }
    }
}
