//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Factura
    {
        public decimal idItem { get; set; }
        public decimal Factura { get; set; }
        public string Nombre { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Importe { get; set; }
    
        public virtual Factura Factura1 { get; set; }
    }
}
