//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoDeFacturas
    {
        public PagoDeFacturas()
        {
            this.FacturasPago = new HashSet<FacturasPago>();
        }
    
        public decimal idPago { get; set; }
        public decimal Sucursal { get; set; }
        public decimal Cliente { get; set; }
        public decimal MetodoPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual ICollection<FacturasPago> FacturasPago { get; set; }
        public virtual FormaDePago FormaDePago { get; set; }
        public virtual Sucursal Sucursal1 { get; set; }
    }
}
