//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendicion
    {
        public Rendicion()
        {
            this.FacturasRendicion = new HashSet<FacturasRendicion>();
        }
    
        public decimal idRendicion { get; set; }
        public decimal Empresa { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal FacturasRendidas { get; set; }
        public decimal ImporteTotal { get; set; }
        public decimal PorcentajeComision { get; set; }
        public decimal TotalComision { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual ICollection<FacturasRendicion> FacturasRendicion { get; set; }
    }
}
