//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.FuncionalidadesRol = new HashSet<FuncionalidadesRol>();
            this.RolesUsuario = new HashSet<RolesUsuario>();
        }
    
        public decimal idRol { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<FuncionalidadesRol> FuncionalidadesRol { get; set; }
        public virtual ICollection<RolesUsuario> RolesUsuario { get; set; }
    }
}
