//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubro
    {
        public Rubro()
        {
            this.Empresa = new HashSet<Empresa>();
        }
    
        public decimal idRubro { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Empresa> Empresa { get; set; }
    }
}
