//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.PagoDeFacturas = new HashSet<PagoDeFacturas>();
            this.UsuariosSucursal = new HashSet<UsuariosSucursal>();
        }
    
        public decimal idSucursal { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public decimal Cod_Postal { get; set; }
        public bool Activa { get; set; }
    
        public virtual ICollection<PagoDeFacturas> PagoDeFacturas { get; set; }
        public virtual ICollection<UsuariosSucursal> UsuariosSucursal { get; set; }
    }
}
