//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoAgil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.RolesUsuario = new HashSet<RolesUsuario>();
            this.UsuariosSucursal = new HashSet<UsuariosSucursal>();
        }
    
        public decimal idUsuario { get; set; }
        public string UserName { get; set; }
        public byte[] Pass { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<RolesUsuario> RolesUsuario { get; set; }
        public virtual ICollection<UsuariosSucursal> UsuariosSucursal { get; set; }
    }
}
